# 11장 데이터 분석을 위한 패키지

사실 패키지 틀린말 라이브러리라고 해야 해

패키지랑 라이브러리 / 프레임워크의 차이는?

*크기, 결과의 개념 헷갈리지 말기   
모듈이 모여 패키지가 되고 패키지가 모여 라이브러리? xxxxxx   
내가 만든 최종 형태   
패키지 묶어서 뭐가 있어    
라이브러리 어떤 기능을 목적으로 (그게 모듈로 되어있을지 패키지가 되어있을지 프로젝트일지 아무도 몰라) 기능적 결과물  
라이브러리 무조건 도구라고 하면 안돼   
결과물인데 얘를 목적으로 두고 쓰면 라이브러리야   

패키지는 모듈의 합   
라이브러리 내가 쓰고 싶은 어쩌구

* 배열과 리스트   
파이썬에서 배열과 리스트 모두 인덱스 값 갖고 있음  
[ ]로 표시


* 배열과 리스트의 차이   
수학에서 배열은 인덱스 값을 가지고 있어   
배열 너무나 명확한 규칙성을 갖고 있어   
한계가 명확히 있어 (개수 안맞으면 에러 남)      
메모리 훨씬 효율적   
배열이면 몇 다시 몇이라고 정확히 알고 있어 크기 정확히 잡아 놓을 수 있음.   
x, y, z 전체의 범위를 잡아놔  


* (그러면 튜플과의 차이?   
튜플은 변경 삭제 어려워   
배열은 그 범위를 뛰어넘는 값 있으면 공간 넓혀야)   

***리스트는 원래 인덱스 값 없는데 파이썬에서 o    
리스트 내 앞사람의 등을 잡는 식으로 기억해 pointer

* 배열과 리스트의 차이2   
배열은 배열간 연산이 가능함   
(리스트 덧셈은(+) 앞의 리스트에 뒤의 리스트 값이 붙어서 한 리스트로 만들어짐   
배열은 배열 전체에 연산이 가능함   
(리스트의 곱셈은(*) 리스트의 요소를 반복함

***

### 11.1 배열 데이터를 효과적으로 다루는 Numpy

누군가 numpy 오픈 소스로 만들었는데 좋아서   
원래는 다운받아서 설치해야 하는데   
Numpy 설치되어 있음

Numpy 다차원 배열 만들기 위해 사용(주로 2차원)

#### 배열 생성하기

In [3]:
import numpy as np

#### 시퀀스 데이터로부터 배열 생성

arr_obj = np.array(seq_data)

In [3]:
import numpy as np

data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

실수가 혼합 된 배열 생성

In [4]:
data2 = [0.1 , 5, 4, 12, 0.5]
a2 = np.array (data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

배열의 속성 표현

In [5]:
a1.dtype

dtype('int32')

In [6]:
a2.dtype

dtype('float64')

데이터를 직접 넣어서 배열 객체 생성

In [11]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

2차원 배열 생성 방법

In [10]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2차원 배열 Numpy를 사용하는 이유 중 1,,,

#### 범위를 지정해 배열 생성

arr_obj = np.arange([start,] stop [,step])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(1,10) #step생략

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5) #stop만

array([0, 1, 2, 3, 4])

reshape를 추가해서 1차 배열을 2차 배열로 변경하기

배열의 원소 개수와 reshape(m,n)의 m*n의 개수가 같아야 해

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

배열의 형태 출력 ndarray.shape

In [33]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [35]:
b2 = np.arange(5)
b2.shape #1열이면 뒤에 안나와

(5,)

arr_obj = np.linspace(start,stop [num])    
범위의 시작과 끝을 지정한 후 데이터의 개수를 지정해 Numpy 배열을 생성   
num생략하면 50

In [4]:
np.linspace(1,10,10) #끝 값이야 range처럼 -1 xxxx

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

0 ~ pi까지 동일한 간격으로 20개로 나누기   
np.pi는 Numpy에서 ㅠ를 입력할 때 이용

In [40]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [47]:
np.linspace(1,25)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

모든 원소가 0과 1인 다차원 배열을 만들기 위해서는 zeros()와 ones()사용

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

단위 행렬 (identity matrix) 생성   
단위 행렬 = n*n인 정사각형 행렬에서 주 대각선이 모두 1이고 나머지가 0인 행렬 eye()

대각선이 모두 1인 행렬 = 1

In [202]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

매트릭스 행렬 / 벡터 1차원 /  팬서플로어? 3차원

#### 배열의 데이터 타입 변환

문자열이 원소인Numpy 배열

In [71]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [205]:
np.array(['1.5', '0.62', '2', '3.14', '3.1415'])

array(['1.5', '0.62', '2', '3.14', '3.1415'], dtype='<U6')

제일 큰 거에 맞춰 자리수 차지

| 기호 | 의미 |
|:-:|:-|
| 'b' | 불, bool |
| 'i' | 기호가 있는 정수, (singned)integer |
| 'u' | 기호가 없는 정수, (unsigned)integer |
| 'f' | 실수, floating-point |
| 'c' | 복소수, complex-floating point |
| 'M' | 날짜, datetime |
| 'O' | 파이썬 객체, (Python)object |
| 'S' 혹은  'a' | 바이트 문자열, (byte)String |
| 'U' | 유니코드, unicode |

헤더   
가운대 정렬 / 왼쪽 정렬

배열의 형 변환 astype()   
num_arr = str_arr.astype(dtype)

문자열을 실수로

In [73]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [74]:
str_a1.dtype

dtype('<U5')

In [75]:
num_a1.dtype

dtype('float64')

문자열을 정수로

In [79]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [81]:
str_a2.dtype

dtype('<U1')

In [80]:
num_a2.dtype

dtype('int32')

실수를 정수로 (소숫점 버림)

In [84]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [85]:
num_f1.dtype

dtype('float64')

In [86]:
num_i1.dtype

dtype('int32')

#### 난수 배열의 생성

rand() = 0과 1 사이의 실수 난수를 갖는 Numpy배열 생성   
rand_num = np.random.rand(d0,d1,d2,...dn)

radiant() = [low, high] 사이의 정수 난수를 갖는 배열을 생성   
rand_num = np.random.randint([low] , high, [size])

In [88]:
np.random.rand(2,3)

array([[0.42049   , 0.81934391, 0.5327983 ],
       [0.78336625, 0.90901426, 0.06767067]])

In [240]:
np.random.rand()

0.536120793676603

In [13]:
np.random.rand(2,3,4) #2 z층 / 3 y행 /4 x열

array([[[0.70582209, 0.95096315, 0.70058459, 0.33367451],
        [0.34115323, 0.79338183, 0.99018116, 0.73418057],
        [0.12209263, 0.12523788, 0.56137258, 0.53522825]],

       [[0.91544105, 0.99091712, 0.56378736, 0.07195116],
        [0.46326821, 0.40194057, 0.25014361, 0.21004151],
        [0.23001174, 0.57963003, 0.5865814 , 0.12735455]]])

In [206]:
np.random.randint(10,size = (3,4))

array([[7, 1, 1, 7],
       [7, 2, 3, 5],
       [5, 6, 4, 6]])

In [254]:
np.random.randint(1,30) #사이즈를 지정하지 않으면 1

9

In [253]:
np.random.randint(1,30, (2,4)) #사이즈를 지정하지 않으면 1

array([[25,  6, 29,  4],
       [23, 11,  1,  7]])

### 배열의 연산

#### 기본 연산

배열의 형태가 같다면 연산이 가능

In [208]:
arr1 = np.array([10,20,30,40]) # 개수 같아야 해
arr2 = np.array([1,2,3,4])

In [98]:
arr1 + arr2

array([11, 22, 33, 44])

In [99]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [100]:
arr1*2

array([20, 40, 60, 80])

In [101]:
arr2**2

array([ 1,  4,  9, 16], dtype=int32)

In [102]:
arr1*arr2

array([ 10,  40,  90, 160])

In [103]:
arr1 / arr2

array([10., 10., 10., 10.])

In [104]:
arr1/2

array([ 5., 10., 15., 20.])

복합연산

In [105]:
arr1 / (arr2 **2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

비교연산

In [106]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

In [124]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

합계 sum()와 평균 mean()

In [126]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

표준편차 std()와 분산var()    
표준편차 = 평균을 중심으로 퍼져있는 정도 (분산 ** 1/2)   
분산 = 변량이 평균으로 부터 떨어져있는 정도 


표준편차와 분산이 평균으로부터 가까울 수록 신뢰도가 높아

In [127]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

최솟값 min()과 최댓값 max()

In [128]:
[arr3.min(), arr3.max()]

[0, 4]

누적합 cumsum()과 누적곱 cumprod()

In [129]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [133]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [134]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

#### 행렬연산

In [148]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [214]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

행렬 곱(matrix product)   
두 개의 행렬에서 한 개의 행렬을 만들어내는 이항연산

In [140]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [142]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [210]:
B.dot(A) #어떤 게 기준이 되는지에 따라 값 달라

array([[4, 9],
       [2, 3]])

*** 직사각형 행렬 곱은 조금 달라

In [2]:
import numpy as np
A = np.array([0,1,2,3,4,5]).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [6]:
A*B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [211]:
A = np.array([0,1,2,3,4,5]).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

전치행렬(transpose matrix)

행과 열을 위치를 바꾸는 것(대각선을 기준으로 바꿔)

In [144]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [150]:
A.transpose()

array([[0, 2],
       [1, 3]])

역행렬(reverse matrix)

행렬의 곱셈에 대한 역원   
#(단위행렬(1)이 되게 하는 값)

In [147]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

행렬식 (dterminant)

1/ AD-BC (AD-BC가 0이면 안돼)

행렬식의 값이 0인 경우에는 역행렬을 가질 수 없다.

In [152]:
np.linalg.det(A)

-2.0

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것

배열명 [위치]

In [157]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [158]:
a1[0]

0

In [159]:
a1[4]

40

원소 변경하기

In [160]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

1차원 배열에서 여러개의 원소 선택하기

In [162]:
a1[[1,3,4]]

array([10, 30, 40])

2차원 배열 생성하기

In [163]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [164]:
a2[0,2]

30

In [165]:
a2[1,2]

60

2차원에서 원소 값 변경

In [184]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

하나만 입력하면 행위치를 지정함

In [168]:
a2[1]

array([40, 50, 60])

2차원에서 특정 행을 변경

In [173]:
a2[1] = np.array([45,55,65]) #배열 지정해서 변경
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [181]:
a2[1] = [47,57,67] #리스트로 변경도 가능
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

2차원 배열에서 여러 원소 선택하기   
배열명 [행위치1, 행_위치2,..행위치[n]], [열_위치1, 열_위치2,...,열위치[n]]

In [184]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [185]:
a2[[0,2],[0,1]]

array([10, 80])

In [189]:
a2[[0,2],[0,2]]

array([10, 95])

배열 [조건]

In [179]:
a = np.array([1,2,3,4,5,6,0])
a[a > 3] #value 값

array([4, 5, 6])

짝수만 출력

In [183]:
a[(a % 2) == 0]

array([2, 4, 6, 0])

배열의 슬라이싱

범위를 지정해 배열의 일부분을 선택하는 슬라이싱   
배열[시작:끝]

In [190]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [191]:
b1[:3]

array([ 0, 10, 20])

In [192]:
b1[2:]

array([20, 30, 40, 50])

슬라이싱으로 원소 변경

In [193]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [195]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

2차 배열에서의 슬라이싱

In [8]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

배열[행시작: 행끝, 열시작: 열끝]

In [237]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [199]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

행을 지정하고 열을 슬라이싱

In [200]:
b2[1][0:2]

array([40, 50])

슬라이싱 된 배열에 값 지정하기

In [9]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [265]:
a = 2345
b = str(a)

In [266]:
b[1]

'3'

In [273]:
a = 3,6,9

In [274]:
str(a)

'(3, 6, 9)'

In [276]:
s = 'dfhela'

In [280]:
s.upper()

'DFHELA'

In [283]:
range(10)

range(0, 10)